import { mkdir, writeFile, cp } from 'node:fs/promises';
import config from './site.config.mjs';
import chineseWeeks from './learning-content.mjs';
import { learningCode } from './learning-code.mjs';

const escape = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 12h14M12 5l7 7-7 7"/></svg>';
const diagonal = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12"/></svg>';
const external = config.github ? `<a href="${escape(config.github)}" target="_blank" rel="noopener noreferrer">GitHub ${diagonal}<span class="sr-only"> (opens in new tab)</span></a>` : '';
function nav(path) { return `<header class="header wrap"><a class="brand" href="/" aria-label="Joker Carter home"><span class="brand-icon">jc<span>.</span></span><span>jokercarter</span></a><nav aria-label="Main navigation"><a ${path.startsWith('/projects')?'aria-current="page"':''} href="/projects/" data-i18n="navProjects">Projects</a><a ${path.startsWith('/learning')?'aria-current="page"':''} href="/learning/" data-i18n="navLearning">Learning</a><a ${path==='/about/'?'aria-current="page"':''} href="/about/" data-i18n="navAbout">About</a>${external}<button class="language-toggle" type="button" aria-label="Switch language" data-language-toggle>中文</button></nav></header>`; }
const footer = `<footer class="wrap footer"><a href="/" class="footer-name">jokercarter<span>.</span></a><span>A little better, one commit at a time.</span><a href="#top">Back to top ↑</a></footer>`;
const contact = `<section class="contact wrap"><div><span class="section-label">WHAT'S NEXT</span><h2>Let’s build something<br><em>worth learning from.</em></h2></div><div class="contact-right"><p>Exploring opportunities at the intersection of AI and software engineering.</p>${config.email ? `<a class="button primary" href="mailto:${escape(config.email)}">Get in touch ${arrow}</a>` : external ? `<a class="button primary" href="${escape(config.github)}" target="_blank" rel="noopener noreferrer">Find me on GitHub ${diagonal}</a>` : '<p>Contact details coming soon.</p>'}</div></section>`;
const grid = `<div class="experiment"><div class="experiment-top"><span><span class="live-dot"></span> THE SHORTEST WAY THERE</span><span>BFS / 01</span></div><div class="path-grid" role="group" aria-label="Interactive pathfinding grid. Select a cell to add or remove a wall."></div><div class="legend"><span><i class="start-dot"></i> Start</span><span><i class="end-dot"></i> Finish</span><span><i class="wall-dot"></i> Wall</span><span class="grid-hint">Click a cell to add a wall</span></div><div class="experiment-bottom"><p id="path-status" role="status" aria-live="polite">Every good idea starts with a path.</p><div><button class="reset-button" type="button" aria-label="Reset grid">Reset</button><button class="run-button" type="button">Find a path ${arrow}</button></div></div></div>`;
const work = `<div class="project-list"><a class="project-row" href="/projects/pathfinder/"><div class="project-number">01 / INTERACTIVE EXPERIMENT</div><div><h3>Pathfinder ${diagonal}</h3><p>An idea you can play with. Explore how breadth-first search finds its way through a grid.</p><div class="tags"><span>JavaScript</span><span>Algorithms</span><span>Interactive</span></div></div><div class="project-art" aria-hidden="true"><span class="mini-path">S ────┐<br>　　　│<br>　┌──┘<br>　└── E</span></div></a><a class="project-row" href="/arena/"><div class="project-number">02 / GAME PROTOTYPE</div><div><h3>Morrow Fields ${diagonal}</h3><p>Explore three original pixel arenas, collect from 13 weapon types, and battle with friends in real time.</p><div class="tags"><span>WebSocket</span><span>FastAPI</span><span>Canvas</span></div></div><div class="project-art" aria-hidden="true"><span class="mini-path">◉ ── ✦<br>　╲　 ╱<br>　　⌁</span></div></a><div class="project-row planned"><div class="project-number">03 / ON THE DRAWING BOARD</div><div><h3>Answers, with evidence.</h3><p>A planned document assistant that answers questions with source citations. The next step in my AI learning journey.</p><div class="tags"><span>RAG</span><span>Python</span><span>Planned</span></div></div><div class="project-art paper-art" aria-hidden="true"><span>“</span><div class="paper-lines"></div></div></div></div>`;
const aboutText = `<div class="about-copy"><p>I’m Joker Carter. I’m learning to turn ideas into useful software, starting with a foundation in Python, data structures, and algorithms.</p><p>My next chapter is AI engineering: understanding the systems around a model, asking better questions, and building things that people can actually use.</p><p>This is my corner of the internet to share that process — the experiments, the lessons, and the work as it develops.</p></div>`;
const home = `<section class="hero wrap"><div class="hero-copy"><h1>Curiosity.<br>Code.<br><em>What’s next.</em></h1><p>Hi, I’m Joker Carter. Exploring AI and software engineering, one thoughtful experiment at a time.</p><a class="button primary" href="/projects/">Explore my work ${arrow}</a></div><div class="hero-experiment">${grid}<p class="experiment-caption"><span>01 — A SMALL EXPERIMENT</span> A shortest path. A place to start.</p></div></section><div class="intro-strip wrap"><span>PYTHON & ALGORITHMS</span><span class="strip-line"></span><span>LEARNING BY BUILDING</span><span class="strip-line"></span><span>AI × SOFTWARE ENGINEERING</span></div><section class="work-section wrap"><div class="section-heading"><div><span class="section-label">THE WORKBENCH</span><h2>Small steps.<br>Working software.</h2></div><a class="text-link" href="/projects/">All projects ${arrow}</a></div>${work}</section><section class="about-section wrap"><div><span class="section-label">BEHIND THE CODE</span><h2>Always a student.<br><em>Building what's next.</em></h2><a class="text-link" href="/about/">A little about me ${arrow}</a></div>${aboutText}</section><section class="learning-teaser wrap"><div><span class="section-label">THE ROADMAP</span><h2>12 weeks of<br><em>learning by building.</em></h2></div><div><p>A practical path from Python foundations to AI applications, production systems, and internship interviews.</p><a class="text-link" href="/learning/">See the full learning plan ${arrow}</a></div></section>${contact}`;
const projects = `<section class="page-intro wrap"><span class="section-label">PROJECTS & EXPERIMENTS</span><h1>The workbench<span>.</span></h1><p>A place for things I’m building, ideas I’m testing, and what comes next. Each project starts with a question.</p></section><section class="wrap work-page" aria-label="Projects">${work}</section>${contact}`;
const about = `<section class="page-intro wrap"><span class="section-label">A LITTLE ABOUT ME</span><h1>Curious by default<span>.</span></h1><p>Learning the fundamentals. Following the questions. Turning understanding into something useful.</p></section><section class="about-section about-page wrap"><div class="monogram" aria-hidden="true">jc<span>.</span><small>JOKER CARTER</small></div>${aboutText}</section><section class="learning wrap"><span class="section-label">MY LEARNING DIRECTION</span><h2>From foundations to applications.</h2><div class="learning-row"><span>01 / FOUNDATION</span><h3>Python & algorithms</h3><p>Building on basic Python, data structures, and algorithmic thinking.</p></div><div class="learning-row"><span>02 / NEXT UP</span><h3>Software engineering</h3><p>Learning APIs, databases, testing, and deployment.</p></div><div class="learning-row"><span>03 / THE DIRECTION</span><h3>AI applications</h3><p>Exploring retrieval, model APIs, and how to evaluate useful AI systems.</p></div><a class="text-link" href="/learning/">Read my full 12-week plan ${arrow}</a>${config.resume ? `<a class="button primary" href="${escape(config.resume)}">View résumé ${arrow}</a>` : ''}</section>${contact}`;
const weeks = [
 ['01','Python engineering, Git & command line','Python project structure, virtual environments, package management, type hints, exceptions, file I/O, JSON, CSV, environment variables, PowerShell/Linux commands, Git branches and commit conventions.','Build a JSON-backed command-line Todo app.','GitHub repository, README, run instructions and at least five meaningful commits.','Install and run it from an empty directory; explain the project structure and each Git operation.'],
 ['02','HTTP, REST APIs & FastAPI','Clients and servers, HTTP methods, URLs, status codes, headers, request bodies, JSON, REST design, FastAPI routes, Pydantic validation, Swagger and pytest basics.','Build a task-management API with create, read, update and delete operations.','API documentation, input validation, error responses and at least five tests.','Operate every endpoint from `/docs`; rerun the test command successfully.'],
 ['03','SQL, databases & ORM','Tables, primary and foreign keys, relationships, CRUD, JOINs, indexes, transactions, SQLite, PostgreSQL, SQLAlchemy and migrations.','Move the Todo API from JSON to a database; add users and task ownership.','Schema diagram, pagination, filtering, sorting and a JOIN query.','Data survives a restart; explain table relationships, indexes and transactions.'],
 ['04','Docker, testing & CI','Images, containers, Dockerfile, Compose, unit and integration tests, logs, `.env` configuration and GitHub Actions.','Finish a production-style Task Management API.','FastAPI + PostgreSQL + SQLAlchemy + pytest + Docker Compose project.','One command starts it; CI runs tests; README guides a new developer through setup.'],
 ['05','Machine-learning foundations','Features, labels, train/validation/test splits, classification, regression, overfitting, underfitting, data leakage, accuracy, Precision, Recall, F1 and cross-validation.','Use NumPy, Pandas and scikit-learn on a public dataset.','Data-cleaning notebook, two model comparisons and error-sample analysis.','Explain the split, metric choice and why the model fails on specific samples.'],
 ['06','PyTorch & neural networks','Tensors, Dataset, DataLoader, layers, activations, loss functions, backpropagation, optimizers, training loops, CPU/GPU and saving/loading models.','Train a text- or image-classification model and write a standalone inference script.','Training curves, best checkpoint, inference script and experiment notes.','Write a training loop independently; explain `train()`, `eval()` and overfitting.'],
 ['07','Transformers, embeddings & model APIs','Tokens, the intuition behind attention, Transformer use cases, embeddings, cosine similarity, Hugging Face basics, model APIs, structured output, timeouts, retries and cost control.','Implement text chunking, embedding generation and a semantic-search API.','FastAPI search endpoint, retrieval examples and a chunking-strategy note.','Explain keyword vs semantic search and record failed searches.'],
 ['08','RAG document Q&A','RAG data flow, document parsing, chunking, vector retrieval, top-k, context assembly, citations, hallucinations, refusal strategies and evaluation sets.','Build a Document Q&A system with uploads, citations and history.','FastAPI backend, small web UI, Docker configuration and at least 30 evaluation questions.','Answers show file and page sources; unsupported questions are not fabricated; results are tabulated.'],
 ['09','Quality, reliability & maintainability','Layered architecture, separation of business and data access, configuration, secret protection, logging, exceptions, mocks, unit/integration tests, async code, timeouts, retries and upload limits.','Refactor the RAG project into API, service, retrieval, storage and configuration modules.','Core-logic tests, structured logs, error handling and upload limits.','No API key in Git; failures return clear responses; core modules can be tested independently.'],
 ['10','Deployment & basic system design','Cloud servers, containers, reverse proxies, HTTPS, health checks, backend/database communication, caching, queues, background jobs, sync vs async and AI-system scaling.','Deploy the RAG project with a health check and architecture diagram.','Reachable demo, deployment guide and a 2–3 minute walkthrough video.','A new user can run or visit it from the README; explain the full request path.'],
 ['11','Portfolio, résumé & project storytelling','GitHub README structure, screenshots, architecture diagrams, technical decisions, honest metrics, English project bullets and STAR stories.','Polish the Task API and RAG repositories.','Two complete repositories, one-page English résumé, GitHub profile and demo video.','Explain the problem, architecture, failure, tests and next improvement for each project.'],
 ['12','Interviews, mocks & applications','Python interviews, HTTP, REST, SQL, indexes, transactions, caching, embeddings, RAG evaluation, system design and behavioral interviews.','Run algorithm, project, AI-fundamentals and behavioral mock interviews.','A 60-second introduction, 2-minute and 8-minute project explanations, tailored résumés.','Complete at least four mocks and submit about 20 targeted applications.']
];
const weekCard = w => { const content = chineseWeeks[Number(w[0])-1]; const chapters = ['概念学习 / Concepts','动手实践 / Build','可交付成果 / Ship','逐项验收 / Check','复盘记录 / Reflection']; return `<article class="week-card" id="week-${w[0]}" lang="zh-CN"><div class="week-marker"><span>WEEK</span><strong>${w[0]}</strong><a class="pdf-link" href="/pdfs/week-${w[0]}.pdf" target="_blank" rel="noopener">打开 PDF ${diagonal}</a></div><div class="week-main"><h3>${escape(content[0])}</h3><p class="week-english" lang="en">${escape(w[1])}</p><div class="week-columns">${['LEARN / 学习','BUILD / 实践','SHIP / 产出','CHECK / 验收'].map((label,i)=>`<div><h4 class="week-label">${label}</h4><p>${escape(content[i+1])}</p></div>`).join('')}</div><div class="chapter-checklist" data-week="${w[0]}"><span class="week-label">CHAPTER PROGRESS / 章节进度</span><div>${chapters.map((name,i)=>`<label><input type="checkbox" data-week="${w[0]}" data-chapter="${i}"><span>${name}</span></label>`).join('')}</div></div></div></article>`; };
const learning = `<section class="page-intro learning-intro wrap"><span class="section-label">THE ROADMAP / 学习路线</span><h1>12 weeks of<br><em>learning by building.</em></h1><p>从 Python 基础到 AI 应用工程：每周都有明确的学习内容、实践任务、可交付成果和验收标准。建议每周投入 20–25 小时。</p><div class="roadmap-stats"><div><strong>20–25h</strong><span>每周投入 / per week</span></div><div><strong>2</strong><span>核心项目 / core projects</span></div><div><strong>100+</strong><span>算法练习 / problems</span></div><div><strong>12</strong><span>周执行 / weeks</span></div></div></section><section class="roadmap wrap"><div class="phase-heading"><span class="phase-number">01</span><div><span class="section-label">SOFTWARE ENGINEERING FOUNDATIONS</span><h2>把代码变成软件。</h2><p>先建立 Python 工程、API、数据库、测试和容器基础。</p></div></div>${weeks.slice(0,4).map(weekCard).join('')}<div class="phase-heading"><span class="phase-number">02</span><div><span class="section-label">AI FOUNDATIONS & APPLICATIONS</span><h2>理解模型，做出应用。</h2><p>学习 ML、PyTorch、Embedding 和 RAG，并把模型接入真正的系统。</p></div></div>${weeks.slice(4,8).map(weekCard).join('')}<div class="phase-heading"><span class="phase-number">03</span><div><span class="section-label">PRODUCTION, PORTFOLIO & JOB SEARCH</span><h2>交付、表达、申请。</h2><p>把项目做得可靠、可部署、可解释，然后准备面试和投递。</p></div></div>${weeks.slice(8).map(weekCard).join('')}</section><section class="outcomes wrap"><div><span class="section-label">END OF THE 12 WEEKS</span><h2>What you should<br><em>be able to show.</em></h2></div><div class="outcome-list"><p><strong>01</strong> 两个完整 GitHub 项目：Task Management API 和带引用、评测的 RAG 文档问答系统。</p><p><strong>02</strong> 至少一个已部署 Demo、架构图、README、演示视频和真实评测记录。</p><p><strong>03</strong> 一页英文简历、GitHub Profile、项目讲解稿、模拟面试记录和持续投递。</p></div></section>${contact}`;
const codeCards = learningCode.map(item => `<article class="code-card notebook" data-week="${item.week}"><div class="code-card-top"><div><span class="section-label">WEEK ${item.week} / PYTHON NOTEBOOK</span><h2>${escape(item.title)}</h2><p>${escape(item.focus)}</p></div><button class="run-all" type="button" data-week="${item.week}">Run all ▶</button></div><div class="notebook-intro">每周一个 Notebook：先运行核心实现，再运行练习单元。代码中的中文注释解释了目的、输入、输出和常见边界。</div>${item.cells.map((cell,index)=>`<section class="notebook-cell" data-week="${item.week}" data-cell="${index}"><div class="cell-toolbar"><span>[${index+1}] ${escape(cell.title)}</span><small>${escape(cell.purpose)}</small><button class="run-cell" type="button" data-week="${item.week}" data-cell="${index}">Run cell ▶</button></div><div class="code-editor"><pre><code>${escape(cell.code)}</code></pre></div><div class="code-output" aria-live="polite">点击 Run cell，在本地 Python 中运行这个单元。</div></section>`).join('')}</article>`).join('');
const codeLab = `<section class="page-intro wrap"><span class="section-label">CODE LAB / 代码实验室</span><h1>Read it.<br><em>Run it. Change it.</em></h1><p>每周一个与学习计划对应的完整 Python 示例。你可以先阅读，再复制、修改，最后点击 Run 在本机运行。示例会从浏览器发送到本地服务，不会上传到外部平台。</p><div class="code-lab-note">运行前请确认本地服务器已经启动。Week 06 如果未安装 PyTorch，会显示安装提示；其余示例只使用 Python 标准库。</div></section><section class="code-lab wrap">${codeCards}</section>`;
const pathfinder = `<section class="page-intro wrap"><a class="text-link" href="/projects/">← Back to projects</a><h1>A path through<br><em>the possibilities.</em></h1><p>Add a few walls. Start a search. Watch breadth-first search explore its neighbors and find a shortest path.</p></section><section class="demo-page wrap">${grid}<div class="demo-explanation"><div><span class="section-label">HOW IT WORKS</span><h2>One layer at a time.</h2></div><div><p>Breadth-first search (BFS) uses a queue to explore nearby cells before moving further away. Every move costs the same, so the first route it finds to the finish is a shortest route.</p><p>Select cells to add or remove walls. The pale green cells show the search; the dark green route shows the result. Reset restores the original grid. You can use Tab and Enter or Space to edit cells with a keyboard.</p><p>This experiment runs entirely in your browser. It does not use AI or send your grid anywhere.</p></div></div></section>${contact}`;
const pages = [['/', 'Joker Carter — Curiosity. Code. What’s next.', home], ['/projects/', 'Projects — Joker Carter', projects], ['/learning/', 'Learning roadmap — Joker Carter', learning], ['/learning/code/', 'Code lab — Joker Carter', codeLab], ['/about/', 'About — Joker Carter', about], ['/projects/pathfinder/', 'Pathfinder — Joker Carter', pathfinder]];
await mkdir('dist', {recursive:true});
const chapterTitles = [
 [['环境与模块','Environments and modules'],['类型、异常与文件','Types, errors and files'],['JSON Todo 实现','JSON Todo implementation'],['Git 与命令行','Git and command line']],
 [['HTTP 请求与响应','HTTP requests and responses'],['Pydantic 与路由','Validation and routing'],['CRUD 与状态码','CRUD and status codes'],['API 测试','API testing']],
 [['表、主外键与关系','Tables, keys and relations'],['查询、JOIN 与分页','Queries, joins and pagination'],['事务与回滚','Transactions and rollback'],['ORM、索引与迁移','ORM, indexes and migrations']],
 [['单元与集成测试','Unit and integration tests'],['日志与配置','Logging and configuration'],['Docker 与 Compose','Docker and Compose'],['CI 与交付文档','CI and delivery documentation']],
 [['数组与数据清洗','Arrays and data cleaning'],['数据划分与泄漏','Splits and leakage'],['模型与交叉验证','Models and cross-validation'],['指标与错误分析','Metrics and error analysis']],
 [['Tensor 与 DataLoader','Tensors and DataLoader'],['反向传播与训练循环','Backpropagation and training'],['验证与过拟合','Validation and overfitting'],['保存、加载与推理','Save, load and inference']],
 [['Token 与 Attention','Tokens and attention'],['Embedding 与余弦','Embeddings and cosine similarity'],['切分与搜索接口','Chunking and search API'],['模型 API 可靠性','Model API reliability']],
 [['解析与来源定位','Parsing and source locations'],['检索与上下文','Retrieval and context'],['引用与拒答','Citations and abstention'],['评测与失败分析','Evaluation and failures']],
 [['分层与接口','Layers and interfaces'],['测试与 Mock','Tests and mocks'],['异步、超时与重试','Async, timeouts and retries'],['上传和密钥保护','Upload and secret protection']],
 [['请求链路与 HTTPS','Request flow and HTTPS'],['缓存策略','Caching strategies'],['队列与后台任务','Queues and background jobs'],['健康检查与部署','Health checks and deployment']],
 [['README 与证据','README and evidence'],['架构与技术取舍','Architecture and tradeoffs'],['英文简历','English resume'],['STAR 与演示','STAR and demos']],
 [['Python 与算法','Python and algorithms'],['系统设计与 AI','System design and AI'],['模拟面试与复盘','Mock interviews and reflection'],['针对性申请','Targeted applications']]
];
await writeFile('public/curriculum.json',JSON.stringify(weeks.map((w,i)=>({week:w[0],title:chineseWeeks[i][0],title_en:w[1],...Object.fromEntries(['learn','build','ship','check'].flatMap((k,j)=>[[k,chineseWeeks[i][j+1]],[k+'_en',w[j+2]]])),chapters:chapterTitles[i].map(([zh,en])=>({zh,en}))})),null,2));
for (const [path,title,body] of pages) {
 const folder = 'dist'+path; await mkdir(folder,{recursive:true});
 await writeFile(folder+'index.html', `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Joker Carter’s personal workbench. Exploring Python, algorithms, AI, and software engineering through hands-on experiments."><meta name="theme-color" content="#f5f4ef"><title>${escape(title)}</title><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/i18n.js" defer></script><script src="/app.js" defer></script></head><body id="top"><a class="skip-link" href="#main">Skip to content</a>${nav(path)}<main id="main">${body}</main>${footer}</body></html>`);
}
await writeFile('dist/404.html', `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Page not found — Joker Carter</title><link rel="stylesheet" href="/styles.css"><body><main class="page-intro wrap"><span class="section-label">404 / A DIFFERENT PATH</span><h1>Lost? Start here.</h1><p>This page doesn’t exist.</p><a class="button primary" href="/">Back home</a></main></body></html>`);
await cp('public', 'dist', { recursive: true, force: true });
console.log(`Built ${pages.length} pages + 404 into dist/`);
