import {useState} from 'react';
import {useLocation,Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import Markdown from './markdown';
import {api,stream,client,useT,ErrorText} from './core';
export default function Assistant(){
 const t=useT(),params=new URLSearchParams(useLocation().search);const [id,setId]=useState(''),[text,setText]=useState(''),[code,setCode]=useState(''),[search,setSearch]=useState(params.get('q')||''),[sources,setSources]=useState<any[]>([]),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[usage,setUsage]=useState<any>(null),[warning,setWarning]=useState('');
 const status=useQuery({queryKey:['ai-status'],queryFn:()=>api('ai/status')});const chats=useQuery({queryKey:['chats'],queryFn:()=>api('chats')});const history=useQuery({queryKey:['chat',id],queryFn:()=>api('chats/'+id),enabled:!!id});const results=useQuery({queryKey:['search',search],queryFn:()=>api('documents/search?q='+encodeURIComponent(search))});
 async function create(){try{const chat=await api('chats','POST',{title:text.slice(0,70)||t('session')});setId(chat.id);await client.invalidateQueries({queryKey:['chats']});return chat.id;}catch(e){setError(String(e));throw e;}}
 async function send(){if(busy||!text.trim())return;setBusy(true);setError('');setAnswer('');setWarning('');setUsage(null);try{const chat=id||await create();await stream('chats/'+chat+'/turn',{text,code,source_ids:sources.map(s=>s.source_id)},event=>{if(event.type==='delta')setAnswer(a=>a+event.text);if(event.type==='error')setError(event.text);if(event.type==='warning')setWarning(event.text);if(event.type==='done'){setUsage(event.usage);if(event.invalid_citations.length)setWarning(t('invalidCitation'));}});await client.invalidateQueries({queryKey:['chat',chat]});setAnswer('');}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <><section className="panel"><div className="toolbar"><strong>{t('connection')}: {status.isPending?t('loading'):status.data?.available?'Connected':'Unavailable'}</strong><button onClick={()=>status.refetch()}>{t('retry')}</button><button disabled={busy||!status.data?.available} onClick={()=>{setId('');setAnswer('');setSources([]);}}>{t('newChat')}</button></div>{status.data?.message&&<p>{status.data.message}</p>}<p>{t('noTools')}</p><small>{status.data?.version}</small></section><div className="toolbar">{chats.data?.map((chat:any)=><button disabled={busy} className={chat.id===id?'':'secondary'} key={chat.id} onClick={()=>{setId(chat.id);setAnswer('');}}>{chat.title}</button>)}</div><ErrorText error={error||history.error}/>{history.data?.map((m:any)=><article key={m.id} className={'panel message '+m.role}><small>{m.role} · {m.status}</small><Markdown>{m.content}</Markdown>{m.role==='assistant'&&JSON.parse(m.sources||'[]').map((s:any)=><p key={s.source_id}><Link to={'/app/documents?id='+s.document_id+'#page-'+s.page}>[S{s.source_id}] {s.name} · {t('page')} {s.page}</Link></p>)}</article>)}{answer&&<article className="panel" aria-live="polite"><Markdown>{answer}</Markdown></article>}{warning&&<p role="alert">{warning}</p>}{usage&&<details><summary>{t('usage')}</summary><pre>{JSON.stringify(usage,null,2)}</pre></details>}<section className="panel"><label>{t('search')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{results.data?.map((s:any)=><label className="check" key={s.source_id}><input type="checkbox" checked={sources.some(x=>x.source_id===s.source_id)} disabled={busy} onChange={e=>setSources(old=>e.target.checked?[...old,s].slice(0,8):old.filter(x=>x.source_id!==s.source_id))}/>{s.name} · {s.page} · S{s.source_id}</label>)}<h3>{t('sources')}</h3>{sources.map(s=><blockquote key={s.source_id}>[S{s.source_id}] {s.name} · {s.page}<p>{s.content}</p></blockquote>)}<p>{t('context')}</p><label>{t('code')}<textarea value={code} onChange={e=>setCode(e.target.value)} maxLength={16000}/></label><label>{t('question')}<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={12000}/></label><div className="toolbar"><button disabled={busy||!status.data?.available||!text.trim()} onClick={send}>{t('send')}</button><button disabled={!busy||!id} onClick={()=>api('chats/'+id+'/stop','POST').catch(e=>setError(String(e)))}>{t('stop')}</button></div></section></>;
}
