import {createContext,useContext} from 'react';
import {QueryClient} from '@tanstack/react-query';
export const client=new QueryClient({defaultOptions:{queries:{retry:false,refetchOnWindowFocus:false}}});
export let csrf='';
export function setCsrf(value:string){csrf=value;}
export async function api(url:string,method='GET',body?:unknown){const response=await fetch('/api/'+url,{method,headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
export async function stream(url:string,body:unknown,receive:(event:any)=>void){const response=await fetch('/api/'+url,{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf},body:JSON.stringify(body)});if(!response.ok)throw Error(await response.text());const reader=response.body!.getReader(),decoder=new TextDecoder();let pending='';try{while(true){const {value,done}=await reader.read();pending+=decoder.decode(value,{stream:!done});const lines=pending.split('\n');pending=lines.pop()!;for(const line of lines)if(line.trim())receive(JSON.parse(line));if(done){if(pending.trim())receive(JSON.parse(pending));break;}}}finally{reader.releaseLock();}}
export function download(name:string,data:string,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function details(record:any){try{const x=JSON.parse(record.body);return x&&typeof x==='object'?x:{body:record.body};}catch{return {body:record.body};}}
export function kernelStream(id:string,code:string,receive:(event:any)=>void){return new Promise<void>((resolve,reject)=>{const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/notebooks/${id}/ws`);let finished=false;socket.onopen=()=>socket.send(JSON.stringify({csrf,code}));socket.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='finished'){finished=true;resolve();}else receive(event);};socket.onerror=()=>reject(Error('Notebook connection failed'));socket.onclose=()=>{if(!finished)reject(Error('Notebook connection closed before completion'));};});}
const words:Record<string,[string,string]>={
 materials:['课程资料管理','Course materials'],dashboard:['概览','Overview'],courses:['学习中心','Learning'],tasks:['任务看板','Tasks'],notes:['学习日志','Notes'],notebooks:['Notebook','Notebooks'],documents:['知识库','Knowledge'],applications:['求职管理','Applications'],projects:['项目管理','Projects'],articles:['文章管理','Articles'],profile:['个人资料','Profile'],ai:['Codex 助手','Codex tutor'],settings:['备份与迁移','Backup & migration'],welcome:['欢迎回来','Welcome back'],setup:['创建管理员','Create administrator'],username:['用户名','Username'],password:['密码（至少 12 位）','Password (12+ characters)'],login:['进入工作台','Enter workbench'],logout:['退出登录','Sign out'],public:['公开网站','Public portfolio'],theme:['深浅主题','Light / dark'],tagline:['让学习、实践和求职连接起来。','Connect learning, building and your next opportunity.'],loading:['加载中…','Loading…'],
 save:['保存','Save'],saved:['已保存','Saved'],saving:['正在保存…','Saving…'],create:['创建','Create'],edit:['编辑','Edit'],cancel:['取消','Cancel'],delete:['删除','Delete'],confirmDelete:['确认删除？','Delete this item?'],title:['标题','Title'],body:['Markdown 内容','Markdown content'],preview:['预览','Preview'],search:['搜索','Search'],all:['全部','All'],status:['状态','Status'],tags:['标签（逗号分隔）','Tags (comma-separated)'],due:['截止/复习日期','Due / review date'],priority:['优先级','Priority'],high:['高','High'],normal:['普通','Normal'],low:['低','Low'],list:['列表','List'],board:['看板','Board'],empty:['还没有记录，从创建第一条开始。','Nothing yet. Create your first entry.'],course:['关联周次','Related week'],draft:['草稿','Draft'],published:['已发布','Published'],todo:['待办','To do'],doing:['进行中','In progress'],done:['完成','Done'],savedStatus:['已收藏','Saved'],applied:['已申请','Applied'],interview:['面试','Interview'],offer:['Offer','Offer'],rejected:['未通过','Rejected'],withdrawn:['已撤回','Withdrawn'],planned:['计划中','Planned'],completed:['已完成','Completed'],
 company:['公司','Company'],role:['岗位','Role'],url:['网址','URL'],interviewAt:['面试时间','Interview time'],reflection:['复盘','Reflection'],export:['导出','Export'],import:['导入','Import'],csv:['导入 CSV','Import CSV'],exportCsv:['导出 CSV','Export CSV'],autosave:['自动保存已开启','Autosave enabled'],recent:['最近活动','Recent activity'],reminders:['到期提醒','Due reminders'],noReminders:['暂时没有到期事项。','No due items.'],minutes:['学习分钟数','Study minutes'],logTime:['记录学习时长','Log study time'],progress:['章节进度','Chapter progress'],totalTime:['累计学习时间','Study time'],learn:['学习','Learn'],build:['实践','Build'],ship:['产出','Ship'],check:['验收','Check'],openNotebook:['打开 Notebook','Open notebook'],pdf:['阅读 / 下载 PDF','Read / download PDF'],review:['复习计划','Review plan'],
 upload:['上传 PDF / TXT / Markdown','Upload PDF / TXT / Markdown'],parsing:['正在解析并建立索引…','Parsing and indexing…'],duplicate:['文件已存在','File already indexed'],indexed:['索引完成','Indexed'],page:['页','Page'],sources:['选中的来源（发送前预览）','Selected sources (preview before sending)'],newChat:['新建独立会话','New independent chat'],question:['问题','Question'],code:['选中的代码（可选）','Selected code (optional)'],send:['发送','Send'],stop:['停止','Stop'],retry:['重新检查连接','Check connection'],context:['仅发送问题、选中片段和代码；会话保留之前的上下文。','Only the question, selected excerpts and code are sent; this chat retains prior context.'],noTools:['学习助手只解释，不执行命令或写文件。','The tutor explains; it does not execute commands or write files.'],usage:['Codex 实际用量','Reported Codex usage'],invalidCitation:['回答含未匹配的来源编号，请核对证据。','The answer contains unmatched source IDs. Check the evidence.'],
 run:['运行单元','Run cell'],runAll:['运行全部','Run all'],restart:['重启内核','Restart kernel'],addCode:['＋代码','+ Code'],addMarkdown:['＋Markdown','+ Markdown'],up:['上移','Move up'],down:['下移','Move down'],running:['运行中…','Running…'],finished:['执行结束','Execution finished'],notebookHelp:['同一 Notebook 共享变量；不同周次使用独立内核。Shift+Enter 运行当前单元。','Cells share variables within a notebook; each week has its own kernel. Shift+Enter runs the focused cell.'],
 backup:['下载数据备份','Download data backup'],restore:['预览备份恢复','Preview backup restore'],merge:['确认合并恢复','Confirm merge restore'],legacy:['旧学习进度','Legacy learning progress'],legacyHelp:['旧进度只导入为里程碑记录，不视为新版章节完成。','Legacy progress becomes milestone records, not completed chapters.'],legacyPreview:['预览浏览器旧进度','Preview browser progress'],legacyImport:['确认导入里程碑','Import milestones'],noSecrets:['备份不含密码、会话或 Codex 凭据。恢复前请先下载一份当前备份。','Backups exclude passwords, sessions and Codex credentials. Download a current backup before restoring.'],architecture:['架构说明','Architecture'],evidence:['测试证据','Test evidence'],screenshot:['截图网址','Screenshot URL'],resume:['简历网址','Resume URL'],email:['联系邮箱','Contact email'],github:['GitHub 地址','GitHub URL'],name:['姓名','Name'],publishHelp:['只有已发布内容会出现在公开网站，项目完成状态另行记录。','Only published content appears publicly. Project completion is tracked separately.'],completion:['完成状态','Completion'],link:['关联记录 ID','Linked record ID'],connection:['Codex 连接','Codex connection'],session:['会话','Session']};
export const Language=createContext<'zh'|'en'>('zh');
export function useT(){const lang=useContext(Language);return (key:string)=>words[key]?.[lang==='zh'?0:1]||key;}
export function ErrorText({error}:{error:unknown}){return error?<p className="error" role="alert">{String(error)}</p>:null;}
