import {useState,useEffect,useRef} from 'react';
import {useLocation,Link} from 'react-router-dom';
import CodeMirror from '@uiw/react-codemirror';
import {python} from '@codemirror/lang-python';
import Markdown from './markdown';
import {api,kernelStream,download,useT,ErrorText} from './core';
const cell=(kind:string)=>({id:crypto.randomUUID(),cell_type:kind,source:'',metadata:{},...(kind==='code'?{execution_count:null,outputs:[]}:{})});
export default function Notebook(){
 const t=useT(),id=new URLSearchParams(useLocation().search).get('week')||'01';
 const [nb,setNb]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const dirty=useRef(false),latest=useRef<any>(null),stop=useRef(false),revision=useRef(0),saveChain=useRef(Promise.resolve());
 useEffect(()=>{let alive=true;api('notebooks/'+id).then(data=>{if(alive){data.cells=data.cells.map((c:any)=>({...c,id:c.id||crypto.randomUUID(),source:Array.isArray(c.source)?c.source.join(''):c.source}));latest.current=data;setNb(data);}}).catch(e=>setError(String(e)));return()=>{alive=false;};},[id]);
 function change(fn:(nb:any)=>any){const value=fn(latest.current);latest.current=value;dirty.current=true;revision.current++;setNb(value);}
 function save(){const data=latest.current,current=revision.current;if(!data)return;saveChain.current=saveChain.current.then(async()=>{try{await api('notebooks/'+id,'PUT',data);if(current===revision.current)dirty.current=false;setMessage(t('saved'));}catch(e){setError(String(e));}});return saveChain.current;}
 useEffect(()=>{if(!nb||busy||!dirty.current)return;const timer=setTimeout(save,700);return()=>clearTimeout(timer);},[nb,busy]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 function edit(index:number,patch:any){change(n=>({...n,cells:n.cells.map((c:any,i:number)=>i===index?{...c,...patch}:c)}));}
 async function execute(index:number){let failed=false;edit(index,{outputs:[],execution_count:null});await kernelStream(id,latest.current.cells[index].source,event=>{const c=event.content;if(event.type==='execute_input')edit(index,{execution_count:c.execution_count});if(['stream','error','display_data','execute_result'].includes(event.type)){if(event.type==='error')failed=true;const output={output_type:event.type,...c};delete output.transient;const old=latest.current.cells[index].outputs;edit(index,{outputs:[...old,output]});}if(event.type==='clear_output')edit(index,{outputs:[]});});return !failed;}
 async function run(index?:number){if(busy)return;setBusy(true);stop.current=false;setError('');setMessage(t('running'));try{if(index!==undefined)await execute(index);else for(let i=0;i<latest.current.cells.length;i++){if(stop.current)break;if(latest.current.cells[i].cell_type==='code'&&!await execute(i))break;}setMessage(t('finished'));}catch(e){setError(String(e));}finally{setBusy(false);save();}}
 function reorder(index:number,offset:number){change(n=>{const cells=[...n.cells],target=index+offset;if(target<0||target>=cells.length)return n;[cells[index],cells[target]]=[cells[target],cells[index]];return {...n,cells};});}
 return <><div className="week-tabs">{Array.from({length:12},(_,i)=><Link aria-current={id===String(i+1).padStart(2,'0')?'page':undefined} key={i} to={'/app/notebooks?week='+String(i+1).padStart(2,'0')}>W{String(i+1).padStart(2,'0')}</Link>)}</div><p>{t('notebookHelp')}</p><div className="toolbar sticky"><strong>Week {id}</strong><button disabled={!nb||busy} onClick={()=>run()}>{t('runAll')}</button><button onClick={async()=>{stop.current=true;try{await api('notebooks/'+id+'/interrupt','POST');}catch(e){setError(String(e));}}}>{t('stop')}</button><button disabled={busy} onClick={async()=>{try{await api('notebooks/'+id+'/restart','POST');setMessage(t('restart'));}catch(e){setError(String(e));}}}>{t('restart')}</button><button disabled={!nb} onClick={save}>{t('save')}</button><button disabled={!nb||busy} onClick={()=>change(n=>({...n,cells:[...n.cells,cell('code')]}))}>{t('addCode')}</button><button disabled={!nb||busy} onClick={()=>change(n=>({...n,cells:[...n.cells,cell('markdown')]}))}>{t('addMarkdown')}</button><button disabled={!nb} onClick={()=>download('week-'+id+'.ipynb',JSON.stringify(nb,null,2))}>{t('export')}</button><label className="file-label">{t('import')}<input type="file" disabled={busy} accept=".ipynb" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const value=JSON.parse(await f.text());await api('notebooks/'+id,'PUT',value);value.cells=value.cells.map((c:any)=>({...c,source:Array.isArray(c.source)?c.source.join(''):c.source}));latest.current=value;setNb(value);dirty.current=false;setMessage(t('saved'));}catch(e){setError(String(e));}}}/></label></div><p role="status">{message}</p><ErrorText error={error}/>{nb?.cells.map((c:any,i:number)=><section className="panel notebook-cell" key={c.id} onKeyDown={e=>{if(e.shiftKey&&e.key==='Enter'&&c.cell_type==='code'){e.preventDefault();run(i);}}}><div className="toolbar"><small>{c.cell_type==='code'?`In [${c.execution_count??' '}]`:'MARKDOWN'}</small><button disabled={busy||i===0} onClick={()=>reorder(i,-1)}>{t('up')}</button><button disabled={busy||i===nb.cells.length-1} onClick={()=>reorder(i,1)}>{t('down')}</button><button disabled={busy} onClick={()=>change(n=>({...n,cells:n.cells.filter((_:any,j:number)=>i!==j)}))}>{t('delete')}</button>{c.cell_type==='code'&&<button disabled={busy} onClick={()=>run(i)}>{t('run')}</button>}</div><CodeMirror aria-label={'Cell '+(i+1)} editable={!busy} value={c.source} extensions={c.cell_type==='code'?[python()]:[]} onChange={value=>edit(i,{source:value})}/>{c.cell_type==='markdown'?<div className="markdown"><Markdown>{c.source}</Markdown></div>:<div className="outputs" aria-live="polite">{c.outputs?.map((o:any,k:number)=><div key={k}>{o.data?.['image/png']&&<img alt="Python plot" src={'data:image/png;base64,'+o.data['image/png']}/>}<pre className={o.output_type==='error'?'error':''}>{o.text||o.traceback?.join('\n').replace(/\x1b\[[0-9;]*m/g,'')||o.evalue||o.data?.['text/plain']}</pre></div>)}</div>}</section>)}</>;
}
