import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import Markdown from 'react-markdown';
import Architecture from './architecture';
import {api,details,ErrorText} from './core';

const safeUrl=(value:string)=>/^(https?:\/\/|\/[^/])/.test(value||'')?value:undefined;
function LinkIcon(){return <span aria-hidden="true">↗</span>}

export default function Portfolio(){
 const [search,setSearch]=useState('');
 const [lang,setLang]=useState(localStorage.getItem('jokercarter.language')||'zh');
 const en=lang==='en',path=location.pathname,kind=path.startsWith('/blog')?'articles':'projects',id=path.split('/')[2];
 const q=useQuery({queryKey:['public',kind],queryFn:()=>api('public/'+kind)});
 const projects=useQuery({queryKey:['public','projects'],queryFn:()=>api('public/projects')});
 const profile=useQuery({queryKey:['public','profile'],queryFn:()=>api('public/profile')});
 const items=(q.data||[]).filter((x:any)=>(!id||id===x.id)&&(x.title+x.body).toLowerCase().includes(search.toLowerCase()));
 const publishedProjects=projects.data||[];
 const completedProjects=publishedProjects.filter((x:any)=>details(x).completion==='completed');
 const ongoingProjects=publishedProjects.filter((x:any)=>details(x).completion!=='completed');
 const featured=[...completedProjects,...ongoingProjects].slice(0,3);
 const profileData=profile.data?.[0] ? details(profile.data[0]) : {};
 const t={navWork:en?'Work':'作品',navWriting:en?'Writing':'文章',navAbout:en?'About':'关于',eyebrow:en?'SOFTWARE ENGINEER · SYSTEMS & PRODUCT':'软件工程师 · 系统与产品',hero:en?'I turn complex ideas into dependable software.':'将复杂想法，交付为可靠的软件。',intro:en?'I design and build web products with a focus on clear architecture, thoughtful user experiences, and systems that are easy to evolve.':'我设计和构建 Web 产品，关注清晰的架构、细致的体验，以及能够持续演进的系统。',seeWork:en?'View selected work':'查看精选项目',reachOut:en?'Let’s talk':'联系我',impact:en?'What I bring':'我能带来的价值',selected:en?'Selected work':'精选项目',allWork:en?'All projects':'全部项目',approach:en?'How I work':'我的工作方式',writing:en?'Notes from the workbench':'工程实践随笔',search:en?'Search projects, technology or tags':'搜索项目、技术或标签',empty:en?'Published work is coming soon.':'已发布的作品即将上线。',detail:en?'Project details':'项目详情',complete:en?'Shipped':'已交付',contact:en?'Get in touch':'保持联系'};
 const switchLanguage=()=>{const value=en?'zh':'en';setLang(value);localStorage.setItem('jokercarter.language',value);};
 const email=profileData.email;
 return <main className="portfolio-site">
  <nav className="portfolio-nav" aria-label="Main navigation"><a className="portfolio-mark" href="/" aria-label="Home">JC<span>.</span></a><div className="portfolio-links"><a href="/portfolio/">{t.navWork}</a><a href="/blog/">{t.navWriting}</a><a href="#about">{t.navAbout}</a></div><div className="portfolio-actions"><a className="nav-workbench" href="/app/">Workbench <LinkIcon/></a><button className="language-toggle" onClick={switchLanguage}>{en?'中文':'EN'}</button></div></nav>
  {!id&&kind==='projects'&&<><section className="hero-section"><div><p className="overline">{t.eyebrow}</p><h1>{t.hero}</h1><p className="hero-copy">{t.intro}</p><div className="hero-actions"><a className="primary-link" href="#work">{t.seeWork} <LinkIcon/></a>{email&&<a className="secondary-link" href={'mailto:'+email}>{t.reachOut}</a>}</div></div><aside className="hero-signal"><p>01 — 03</p><strong>{en?'Product-minded engineering':'产品思维的工程实践'}</strong><span>{en?'From a rough brief to a working, testable system.':'从模糊需求，到可验证、可交付的系统。'}</span></aside></section><section className="value-section"><p className="section-label">{t.impact}</p><div className="value-grid"><article><span>01</span><h2>{en?'Build for people':'为用户而构建'}</h2><p>{en?'Translate real needs into interfaces that feel focused, fast, and easy to use.':'把真实需求转化为专注、快速、易用的界面。'}</p></article><article><span>02</span><h2>{en?'Engineer for change':'为变化而设计'}</h2><p>{en?'Create maintainable foundations with clear boundaries, useful documentation, and practical tests.':'用清晰边界、有效文档和务实测试，打下可维护的基础。'}</p></article><article><span>03</span><h2>{en?'Ship with care':'对交付负责'}</h2><p>{en?'Make decisions visible, validate the important paths, and improve through feedback.':'让决策可追溯，验证关键路径，并通过反馈持续迭代。'}</p></article></div></section><section className="work-section" id="work"><div className="section-heading"><div><p className="section-label">{t.selected}</p><h2>{en?'A few things I’ve made.':'一些已经做出来的事。'}</h2></div><a href="/portfolio/">{t.allWork} <LinkIcon/></a></div><ErrorText error={projects.error}/><div className="project-grid">{featured.length?featured.map((r:any)=><ProjectCard key={r.id} record={r} en={en} complete={t.complete}/>):<article className="project-placeholder"><span>⌘</span><h3>{t.empty}</h3><p>{en?'Publish projects from the private workbench and they will appear here.':'在私人工作台发布项目后，它们会显示在这里。'}</p></article>}</div></section><section className="process-section"><div><p className="section-label">{t.approach}</p><h2>{en?'The details are the product.':'细节，才是产品本身。'}</h2></div><div className="process-copy"><p>{en?'Good software is more than a feature list. I work across discovery, interface design, implementation, and verification to make the important decisions intentional.':'好的软件不止是一张功能清单。我贯穿需求理解、界面设计、实现与验证，让重要决策都有据可循。'}</p><div className="tech-tags"><span>TypeScript</span><span>React</span><span>Python</span><span>API Design</span><span>Testing</span><span>AI Workflows</span></div></div></section></>}
  {(id||kind==='articles')&&<section className="listing-section"><p className="section-label">{id?t.detail:kind==='articles'?t.writing:t.allWork}</p><h1>{id?(items[0]?.title||t.detail):kind==='articles'?t.writing:t.allWork}</h1>{!id&&<input className="project-search" aria-label="Search" placeholder={t.search} value={search} onChange={e=>setSearch(e.target.value)}/>}<ErrorText error={q.error}/>{!q.isPending&&!items.length&&<p className="empty">{t.empty}</p>}<div className="listing-grid">{items.map((r:any)=><ProjectCard key={r.id} record={r} en={en} complete={t.complete} full={!!id} article={kind==='articles'}/>)}</div></section>}
  <footer id="about" className="portfolio-footer"><div><p className="section-label">{t.contact}</p><h2>{profile.data?.[0]?.title||(en?'Let’s build something useful.':'一起做点有价值的事。')}</h2><Markdown>{profileData.body||(en?'I’m always interested in thoughtful product and engineering conversations.':'我始终乐于交流产品与工程实践。')}</Markdown></div><div className="footer-links">{email&&<a href={'mailto:'+email}>{email} <LinkIcon/></a>}{safeUrl(profileData.github)&&<a href={safeUrl(profileData.github)} target="_blank" rel="noreferrer">GitHub <LinkIcon/></a>}{safeUrl(profileData.resume)&&<a href={safeUrl(profileData.resume)} target="_blank" rel="noreferrer">{en?'Resume':'简历'} <LinkIcon/></a>}</div><p className="copyright">© {new Date().getFullYear()} Joker Carter · Built with intent.</p></footer>
 </main>;
}

function ProjectCard({record,en,complete,full,article}:{record:any,en:boolean,complete:string,full?:boolean,article?:boolean}){
 const d=details(record),url=safeUrl(d.url),github=safeUrl(d.github),screenshot=safeUrl(d.screenshot),href='/'+(article?'blog':'portfolio')+'/'+record.id;
 return <article className={'project-card '+(full?'project-card-full':'')}>
  {screenshot?<img src={screenshot} alt={record.title}/>:<div className="project-art"><span>{(d.tags||'SWE').split(',')[0].trim().slice(0,4)}</span></div>}
  <div className="project-content"><div className="card-meta"><span>{d.tags||'ENGINEERING'}</span>{!article&&<span className="status-dot">{d.completion==='completed'?complete:(en?'In progress':'进行中')}</span>}</div><h2><a href={href}>{record.title}</a></h2><Markdown>{d.body||record.body}</Markdown>{full&&d.architecture&&<><h3>{en?'Architecture':'架构'}</h3><Architecture source={d.architecture}/></>}{full&&d.evidence&&<><h3>{en?'Quality evidence':'质量证明'}</h3><Markdown>{d.evidence}</Markdown></>}<div className="card-links"><a href={href}>{en?'Read case study':'阅读案例'} <LinkIcon/></a>{url&&<a href={url} target="_blank" rel="noreferrer">Demo <LinkIcon/></a>}{github&&<a href={github} target="_blank" rel="noreferrer">GitHub <LinkIcon/></a>}</div></div>
 </article>;
}
