import React,{useState,useEffect,useContext,useRef} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import Markdown from './markdown';
import Materials from './materials';
import Architecture from './architecture';
import {DocumentRelations,LinkedDocuments} from './relations';
import {api,csrf,client,download,details,Language,useT,ErrorText} from './core';
const refresh=()=>client.invalidateQueries();
export function Dashboard(){
 const t=useT(),[error,setError]=useState('');const q=useQuery({queryKey:['dashboard'],queryFn:()=>api('dashboard')});
 const r=useQuery({queryKey:['reminders'],queryFn:async()=>{const kinds=['tasks','applications','notes','progress','study'];return (await Promise.all(kinds.map(k=>api('resources/'+k)))).flat();}});
 const rows=r.data||[],due=rows.filter((x:any)=>{const d=details(x);return x.status!=='done'&&(d.due||d.interview)&&new Date(d.due||d.interview).getTime()<=Date.now()+86400000;});
 const minutes=rows.filter((x:any)=>x.kind==='study').reduce((s:number,x:any)=>s+Number(details(x).minutes||0),0);
 return <><div className="stats"><article><small>{t('progress')}</small><strong>{rows.filter((x:any)=>x.kind==='progress'&&x.status==='done').length}</strong></article><article><small>{t('totalTime')}</small><strong>{minutes}<small> min</small></strong></article><article><small>{t('reminders')}</small><strong>{due.length}</strong></article></div><form className="panel inline-form" onSubmit={async e=>{e.preventDefault();try{await api('resources/study','POST',{title:new Date().toLocaleDateString(),body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))),status:'done'});refresh();}catch(e){setError(String(e));}}}><label>{t('minutes')}<input name="minutes" type="number" min="1" max="1440" required/></label><button>{t('logTime')}</button></form><ErrorText error={error||q.error||r.error}/><div className="two-col"><section className="panel"><h2>{t('reminders')}</h2>{!due.length&&<p>{t('noReminders')}</p>}{due.map((x:any)=><p key={x.id}><Link to={'/app/'+(x.kind==='progress'?'courses':x.kind)}>{x.title}</Link> · {details(x).due||details(x).interview}</p>)}</section><section className="panel"><h2>{t('recent')}</h2>{!q.data?.activity?.length&&<p>{t('empty')}</p>}{q.data?.activity?.slice(0,12).map((x:any)=><p key={x.id}>{x.action}<small> · {new Date(x.created*1000).toLocaleString()}</small></p>)}</section></div></>;
}
const states=(kind:string)=>kind==='tasks'?['todo','doing','done']:kind==='applications'?['saved','applied','interview','offer','rejected','withdrawn']:['draft','published'];
export function Records({kind}:{kind:string}){
 const t=useT();const q=useQuery({queryKey:[kind],queryFn:()=>api('resources/'+kind)});
 const [search,setSearch]=useState(new URLSearchParams(window.location.search).get('q')||''),[filter,setFilter]=useState(''),[priority,setPriority]=useState(''),[board,setBoard]=useState(false),[editing,setEditing]=useState<any>(null),[error,setError]=useState('');
 const filtered=(q.data||[]).filter((r:any)=>(r.title+r.body).toLowerCase().includes(search.toLowerCase())&&(!filter||r.status===filter)&&(!priority||details(r).priority===priority));
 async function changeStatus(r:any,status:string){try{await api('resources/'+kind+'/'+r.id,'PUT',{...r,status});refresh();}catch(e){setError(String(e));}}
 function card(r:any){const d=details(r);return <article className="panel record" key={r.id}><div className="toolbar"><span className="badge">{t(r.status==='saved'?'savedStatus':r.status)}</span>{d.priority&&<span>{t(d.priority)}</span>}{d.completion&&<span>{t(d.completion)}</span>}</div><h2>{r.title}</h2>{d.company&&<p>{d.company} · {d.role}</p>}{d.due&&<p>{t('due')}: {d.due}</p>}{d.interview&&<p>{t('interviewAt')}: {d.interview}</p>}{d.tags&&<p className="muted">{d.tags}</p>}<Markdown>{d.body||''}</Markdown>{d.reflection&&<Markdown>{d.reflection}</Markdown>}<LinkedDocuments recordId={r.id}/><small>ID: {r.id}</small><div className="toolbar"><select aria-label={t('status')+' '+r.title} value={r.status} onChange={e=>changeStatus(r,e.target.value)}>{states(kind).map(s=><option key={s} value={s}>{t(s==='saved'?'savedStatus':s)}</option>)}</select><button onClick={()=>setEditing(r)}>{t('edit')}</button><button className="secondary" onClick={async()=>{if(!confirm(t('confirmDelete')))return;try{await api('resources/'+kind+'/'+r.id,'DELETE');refresh();}catch(e){setError(String(e));}}}>{t('delete')}</button></div></article>;}
 return <><div className="toolbar"><button onClick={()=>setEditing({id:'',title:'',body:'{}',status:states(kind)[0]})}>{t('create')}</button>{kind==='tasks'&&<button className="secondary" onClick={()=>setBoard(!board)}>{t(board?'list':'board')}</button>}{kind==='applications'&&<><a className="button" href="/api/applications/export">{t('exportCsv')}</a><label className="file-label">{t('csv')}<input type="file" accept=".csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await fetch('/api/applications/import',{method:'POST',headers:{'x-csrf-token':csrf},body:f});const d=await r.json();if(!r.ok)throw Error(d.detail);refresh();}catch(e){setError(String(e));}}}/></label></>}</div><div className="filters"><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={t('status')} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{t('all')}</option>{states(kind).map(s=><option key={s} value={s}>{t(s)}</option>)}</select>{kind==='tasks'&&<select aria-label={t('priority')} value={priority} onChange={e=>setPriority(e.target.value)}><option value="">{t('all')}</option>{['high','normal','low'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select>}</div><ErrorText error={error||q.error}/>{editing&&<RecordEditor key={editing.id||'new'} kind={kind} record={editing} close={()=>setEditing(null)}/>} {!filtered.length&&<p className="empty">{t('empty')}</p>}{board?<div className="kanban">{states(kind).map(s=><section key={s}><h2>{t(s)}</h2>{filtered.filter((r:any)=>r.status===s).map(card)}</section>)}</div>:filtered.map(card)}</>;
}
function RecordEditor({kind,record,close}:{kind:string,record:any,close:()=>void}){
 const t=useT(),[title,setTitle]=useState(record.title),[data,setData]=useState<any>({...(kind==='tasks'?{priority:'normal'}:{}),...(kind==='projects'?{completion:'planned'}:{}),...details(record)}),[status,setStatus]=useState(record.status),[message,setMessage]=useState(''),[error,setError]=useState('');const id=useRef(record.id),dirty=useRef(false),queue=useRef(Promise.resolve()),latest=useRef<any>(null);
 latest.current={title,body:JSON.stringify(data),status};
 function update(key:string,value:string){dirty.current=true;setData((d:any)=>({...d,[key]:value}));}
 function save(){const snapshot=latest.current;if(!snapshot.title.trim())return Promise.resolve();setMessage(t('saving'));queue.current=queue.current.then(async()=>{try{const r=await api('resources/'+kind+(id.current?'/'+id.current:''),id.current?'PUT':'POST',snapshot);if(r.id)id.current=r.id;if(JSON.stringify(snapshot)===JSON.stringify(latest.current))dirty.current=false;setMessage(t('saved'));refresh();}catch(e){setError(String(e));}});return queue.current;}
 useEffect(()=>()=>{if(kind==='notes'&&dirty.current)save();},[]);
 useEffect(()=>{if(kind!=='notes'||!dirty.current)return;const timer=setTimeout(save,900);return()=>clearTimeout(timer);},[title,data,status]);
 const fields=kind==='applications'?['company','role','url','due','interviewAt','tags','reflection']:kind==='tasks'?['priority','due','tags','course']:kind==='notes'?['course','due','tags']:kind==='projects'?['tags','url','github','screenshot','architecture','evidence','completion']:kind==='profile'?['email','github','resume']:['tags','course','url'];
 return <section className="panel editor"><h2>{t('edit')}</h2><form onSubmit={e=>{e.preventDefault();save();}}><label>{t('title')}<input required value={title} onChange={e=>{dirty.current=true;setTitle(e.target.value);}}/></label><div className="field-grid">{fields.map(field=>{const key=field==='interviewAt'?'interview':field;return <label key={field}>{t(field)}{field==='priority'||field==='completion'?<select aria-label={t(field)} value={data[key]|| (field==='priority'?'normal':'planned')} onChange={e=>update(key,e.target.value)}>{(field==='priority'?['normal','high','low']:['planned','completed']).map(s=><option key={s} value={s}>{t(s)}</option>)}</select>:<input type={field==='due'?'date':field==='interviewAt'?'datetime-local':field==='email'?'email':'text'} value={data[key]||''} onChange={e=>update(key,e.target.value)}/>}</label>;})}</div><label>{t('body')}<textarea value={data.body||''} onChange={e=>update('body',e.target.value)}/></label><label>{t('status')}<select aria-label={t('status')} value={status} onChange={e=>{dirty.current=true;setStatus(e.target.value);}}>{states(kind).map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label>{!['tasks','applications','notes'].includes(kind)&&<p>{t('publishHelp')}</p>}<div className="toolbar"><button>{t('save')}</button><button type="button" className="secondary" onClick={async()=>{if(dirty.current&&title.trim())await save();close();}}>{t('cancel')}</button><span role="status">{message}</span></div>{kind==='notes'&&<small>{t('autosave')}</small>}</form><ErrorText error={error}/><details open><summary>{t('preview')}</summary><h2>{title}</h2><Markdown>{data.body||''}</Markdown>{data.architecture&&<Architecture source={data.architecture}/>}{data.evidence&&<Markdown>{data.evidence}</Markdown>}</details></section>;
}
export function Courses(){
 const [checked,setChecked]=useState<Record<string,boolean>>({});
 const [reviews,setReviews]=useState<Record<string,string>>({});
 const t=useT(),lang=useContext(Language),[error,setError]=useState('');const q=useQuery({queryKey:['curriculum'],queryFn:()=>api('curriculum')});const progress=useQuery({queryKey:['progress'],queryFn:()=>api('resources/progress')});const notes=useQuery({queryKey:['notes'],queryFn:()=>api('resources/notes')});
 async function mark(id:string,done:boolean){setChecked(values=>({...values,[id]:done}));const previous=progress.data||[],old=previous.find((r:any)=>r.title===id);try{await api('resources/progress'+(old?'/'+old.id:''),old?'PUT':'POST',{title:id,body:'{}',status:done?'done':'todo'});await refresh();}catch(e){setChecked(values=>({...values,[id]:!done}));setError(String(e));}}
 return <><Materials/><p>12 weeks · 20–25 h / week · Task API + Document Q&A · Planned</p><ErrorText error={error||q.error}/>{q.data?.map((w:any)=><section className="panel" key={w.week}><small>WEEK {w.week}</small><h2>{lang==='zh'?w.title:w.title_en}</h2><div className="toolbar"><a href={'/pdfs/week-'+w.week+'.pdf'} target="_blank" rel="noreferrer">{t('pdf')}</a><Link to={'/app/notebooks?week='+w.week}>{t('openNotebook')}</Link></div>{['learn','build','ship','check'].map(key=><div key={key}><h3>{t(key)}</h3><p>{w[key+(lang==='en'?'_en':'')]||w[key]}</p></div>)}<LinkedDocuments course={w.week}/><h3>{t('progress')}</h3>{w.chapters.map((c:any,i:number)=>{const id=`week-${w.week}-chapter-${i+1}`;return <label className="check" key={id}><input type="checkbox" checked={checked[id]??(progress.data?.some((r:any)=>r.title===id&&r.status==='done')||false)} onChange={e=>mark(id,e.target.checked)}/>{lang==='zh'?c.zh:c.en}</label>;})}<label>{t('review')}<input aria-label={'review-'+w.week} type="date" value={reviews[w.week]??(details(progress.data?.find((r:any)=>r.title==='review-'+w.week)||{body:'{}'}).due||'')} onChange={async e=>{const date=e.target.value;setReviews(old=>({...old,[w.week]:date}));try{const title='review-'+w.week,old=progress.data?.find((r:any)=>r.title===title);await api('resources/progress'+(old?'/'+old.id:''),old?'PUT':'POST',{title,status:'todo',body:JSON.stringify({due:date})});refresh();}catch(e){setError(String(e));}}}/></label>{notes.data?.filter((n:any)=>String(details(n).course).padStart(2,'0')===w.week).map((n:any)=><p key={n.id}><Link to="/app/notes">{n.title}</Link></p>)}</section>)}</>;
}
export function Documents(){
 const t=useT(),location=useLocation();const [search,setSearch]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState(new URLSearchParams(location.search).get('id')||''),[error,setError]=useState('');
 const q=useQuery({queryKey:['documents'],queryFn:()=>api('documents')});const results=useQuery({queryKey:['search',search],queryFn:()=>api('documents/search?q='+encodeURIComponent(search))});const doc=useQuery({queryKey:['document',selected],queryFn:()=>api('documents/'+selected),enabled:!!selected});
 useEffect(()=>{if(doc.data&&location.hash)document.getElementById(location.hash.slice(1))?.scrollIntoView();},[doc.data,location.hash]);
 return <><label className="panel file-label">{t('upload')}<input type="file" accept=".pdf,.md,.txt" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setMessage(t('parsing'));try{const r=await fetch('/api/documents',{method:'POST',headers:{'x-csrf-token':csrf,'x-filename':encodeURIComponent(f.name)},body:f});const d=await r.json();if(!r.ok)throw Error(d.detail);setMessage(t(d.duplicate?'duplicate':'indexed'));refresh();setSelected(d.id);}catch(e){setError(String(e));setMessage('');}}}/></label><p role="status">{message}</p><ErrorText error={error||q.error||doc.error}/><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/>{results.data?.map((r:any)=><article className="panel" key={r.source_id}><button onClick={()=>setSelected(r.document_id)}>{r.name} · {t('page')} {r.page} · S{r.source_id}</button><p>{r.content}</p><Link to={'/app/ai?source='+r.source_id+'&q='+encodeURIComponent(search)}>{t('ai')}</Link></article>)}<div className="toolbar">{q.data?.map((d:any)=><button className="secondary" key={d.id} onClick={()=>setSelected(d.id)}>{d.name}</button>)}</div>{doc.data&&<article className="panel"><h2>{doc.data.name}</h2><DocumentRelations key={selected} documentId={selected}/>{doc.data.pages.map((page:string,i:number)=><section id={'page-'+(i+1)} key={i}><h3>{t('page')} {i+1}</h3><pre className="document-text">{page}</pre></section>)}</article>}</>;
}
export function Settings(){
 const t=useT(),[backup,setBackup]=useState(''),[preview,setPreview]=useState<any>(null),[legacy,setLegacy]=useState<any>(null),[message,setMessage]=useState('');
 return <><section className="panel"><h2>{t('backup')}</h2><p>{t('noSecrets')}</p><a className="button" href="/api/backup">{t('backup')}</a><label>{t('restore')}<input type="file" accept=".json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;const text=await f.text();setBackup(text);setPreview(await api('backup/preview','POST',JSON.parse(text)));}catch(e){setMessage(String(e));}}}/></label>{preview&&<><pre>{JSON.stringify(preview,null,2)}</pre><button onClick={async()=>{try{const r=await fetch('/api/backup/restore',{method:'POST',headers:{'Content-Type':'application/json','x-csrf-token':csrf,'x-restore-confirm':'merge'},body:backup});const d=await r.json();if(!r.ok)throw Error(d.detail);setMessage(t('saved'));setPreview(null);refresh();}catch(e){setMessage(String(e));}}}>{t('merge')}</button></>}</section><section className="panel"><h2>{t('legacy')}</h2><p>{t('legacyHelp')}</p><button onClick={()=>{try{setLegacy(JSON.parse(localStorage.getItem('jokercarter.learning.progress.v1')||'{}'));}catch(e){setMessage(String(e));}}}>{t('legacyPreview')}</button>{legacy&&<><pre>{JSON.stringify(legacy,null,2)}</pre><button onClick={async()=>{try{const existing=await api('resources/legacy');for(const [title,value] of Object.entries(legacy)){if(value&&!existing.some((r:any)=>r.title===title))await api('resources/legacy','POST',{title,status:'milestone',body:JSON.stringify({source:'jokercarter.learning.progress.v1',value})});}setMessage(t('saved'));setLegacy(null);refresh();}catch(e){setMessage(String(e));}}}>{t('legacyImport')}</button></>}</section><p role="status">{message}</p><a href="/docs" target="_blank" rel="noreferrer">OpenAPI</a></>;
}
